-- TePal News now uses Schema v1. Run this file instead:
--   supabase-schema-v1.sql
-- It defines: profiles (user_id, display_name, avatar_url), posts (author_id, type enum, post_media, comments, post_likes), and the posts_feed view for the app.
